language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t somuy/multi-docker -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true somuy/multi-docker yarn test

after_success:
  - docker build -t somuy/multi-client ./client
  - docker build -t somuy/multi-nginx ./nginx
  - docker build -t somuy/multi-server ./server
  - docker build -t somuy/multi-worker ./worker 
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push somuy/multi-client
  - docker push somuy/multi-nginx
  - docker push somuy/multi-server
  - docker push somuy/multi-worker